### ISSUE TITLE
problem with use php-phantomjs 

### ISSUE THREAD

**Issue by mob2005** [jonnnnyw/php-phantomjs#1]
i cant use this script .. 
when i call my page in browser this error accourd 

Fatal error: Class 'JonnyW\PhantomJs\Client' not found in C:\xampp\htdocs\read\test\src\a.php on line 4

how i install and use php-phantomjs

**Comment by Jageen** [comment]
Replace 
use JonnyW\PhantomJs\Client;

with

require 'vendor/autoload.php';
use JonnyW\PhantomJs\Client;

Solved my problem.
Reference :-> http://stackoverflow.com/questions/28939044/php-phantomjs-not-loading-in-class-through-composer
