### ISSUE TITLE
PhantomJS scrape not returning visible page contents

### ISSUE THREAD

**Issue by secondarywalrus** [jonnnnyw/php-phantomjs#100]
Let me start by saying I don't think this isn't any sort of bug, but more likely just a configuration issue on my end that I haven't been able to solve - and I'm not sure where else to ask the question. If this isn't an appropriate place, please let me know and I will gladly do that instead.

I started using PhantomJS last month with great success, and love how easy it was to get it working for the first application I set up. I then tried writing a simple PHP script to scrape data from my Garmin Connect account, and have been running into issues.  

The first problem I had was with the HTTPS connection, but I found the "addOption('--ssl-protocol=any')" to get that working and began getting a valid status returned.  However, the data that actually comes back in the scrape doesn't contain most of what's display on the page.  

Here's an example: https://connect.garmin.com/modern/activity/1157027243
The "calories" display, for example (365 C) does not appear anywhere in the content that's returned. I don't know enough about how that garmin page is set up to know where to look next (Like, I'm not sure if its not pulling that data because of the way it's being rendered, or because it's part of some frame element or something - the bulk of my web knowledge is a bit out of date.)

Any direction that could be provided to know how I might work around this would be much appreciated, and thanks again for this great tool!

**Comment by jonnnnyw** [comment]
A few people have had the same issue and it is due to the request not waiting until all the elements on the page are loaded before returning the response.

A temporary work around is to add a delay to the page load:

```
$delay = 5; // In seconds
    
$request = $client->getMessageFactory()->createCaptureRequest('http://jonnyw.me');
$request->setDelay($delay);
```

[Documentation](http://jonnnnyw.github.io/php-phantomjs/4.0/3-usage/#delay-page-render)

There is an [issue](https://github.com/jonnnnyw/php-phantomjs/issues/85) relating to this issue that has some other suggestions you could try.

I am looking into a more elegant solution to this.

**Comment by secondarywalrus** [comment]
Thank you so much, that is working for me!

**Comment by psycholyzern** [comment]
Hi @jonnnnyw I'm trying to not to open a new issue so hope you can lend me a quick help.

I have tried applying the delay and make a screenshot. It is working, your website fully loaded in the screenshot
http://i.imgur.com/dXf2566.jpg

But whenever I echo the content, I got this
http://i.imgur.com/zjF2Hp1h.jpg

This is my code

```
<?php
    require("vendor/autoload.php");
    use JonnyW\PhantomJs\Client;

    $client = Client::getInstance();

    $delay = 5;

    $request = $client->getMessageFactory()->createRequest();
    $request->setMethod('GET');
    $request->setUrl('http://jonnyw.me');
    $request->setDelay($delay);

    $response = $client->getMessageFactory()->createResponse();

    $client->send($request, $response);

    if($response->getStatus() === 200) {
        echo $response->getContent();
    }
```
