### ISSUE TITLE
Running in parallel causes procedure corruption

### ISSUE THREAD

**Issue by maxiwheat** [jonnnnyw/php-phantomjs#101]
We run a program in parallel (multiple instances of PHP running a script) that call php phantomjs. I think we end up in situations where the content of the generated script is corrupted because two process try to write to the same file. Here is the end of a script found in /tmp :

```
system.stderr.write(debug.join('\\n') + '\\n');
system.stdout.write(JSON.stringify(response, undefined, 4));

phantom.exit();

};

m.exit();

};
```

See how it ends, `m.exit();` is not an actual command... it looks more like the end of `phantom.exit();` appended to the file.

I think the error comes from how the unique names are generated (using `uniqid`)

**Comment by jonnnnyw** [comment]
Yeah, `uniqid` is time based so you are probably right. I will ditch it and use something else.

Do you have a simple way to replicate the issue so that I can test it?

**Comment by maxiwheat** [comment]
Sorry no, happens rarely ... but has happen 2 times in the past 2 or 3 weeks, it's very hard to reproduce, but I ended looking at the generated script since we run 2 process in parallel with Gearman. Running `htop` in console I noticed that `phantomjs /tmp/5728c811e5ad4` appeared twice which should not happen, that gave me the idea of a possible "overlap" of temp file names.

**Comment by jonnnnyw** [comment]
I have replaced `uniqid` with a (hopefully) more random solution. This has been released in v4.5 so let me know if you have any further issues with it.

**Comment by maxiwheat** [comment]
Look like to work, thanks a lot

**Comment by batyrmastyr** [comment]
@jonnnnyw You'd rather send getmypid() as $prefix parameter to uniqid(). On top of that, there is $more_entropy parameter just in case if someone will run script using pthreads.
Mt_rand() just makes issue undebugable, moreover calling md5() over mt_rand() result just wastes cpu without any benefit.
