### ISSUE TITLE
// comments break procedure partials

### ISSUE THREAD

**Issue by Milkdog** [jonnnnyw/php-phantomjs#103]
Using `//` comments in a procedure cause it to break on validation due to it putting everything on one line before validation procedure.

Only `/* Comment */` style comments work.

**Comment by jonnnnyw** [comment]
Minifying the script before validation was a workaround to avoid false positives so I will look into removing that.

**Comment by jonnnnyw** [comment]
This has now been fixed in v4.5. Let me know if you have any further issues.
