### ISSUE TITLE
PHP Fatal error:  Call to undefined method JonnyW\PhantomJs\Client::getProcedureCompiler()

### ISSUE THREAD

**Issue by AdriwanKenoby** [jonnnnyw/php-phantomjs#108]
Hello,

I am working on OroCRM which is based on the symfony framework.

I have declared a service,

`<?php

namespace Sinabs\MonitoringBundle\Services;

use JonnyW\PhantomJs\Client;

class Phantom {

    protected $client;
    protected $request;
    protected $response;
    
    public function __construct() {
        $this->client = Client::getInstance();
        $this->client->getProcedureCompiler()->disableCache();
    }

    public function load($url) {
        /**
         * @see JonnyW\PhantomJs\Http\Request
         * */
        $this->request = $this->client->getMessageFactory()->createRequest($url, 'GET');
        /**
         * @see JonnyW\PhantomJs\Http\Response 
         * */
        $this->response = $this->client->getMessageFactory()->createResponse();
        // Send the request
        $this->client->send($this->request, $this->response);
    }

    public function isHttpCodeValid() {
        $http_code = $this->response->getStatus();
        return ($http_code != 200 && $http_code != 304) ? false : true;
    }

    public function getHttpCode() {
        return $this->response->getStatus();
    }
    
    public function getContent() {
        return $this->response->getContent();
    }
}
`
In my composer.json, i have those dependencies : 
        "jonnyw/php-phantomjs": "4.*",
        "jerome-breton/casperjs-installer": "dev-master",
        "phpcasperjs/phpcasperjs": "^1.0"

**Comment by jonnnnyw** [comment]
Which version of the library have you got installed? There was a bug in 4.0 where `getProcedureCompiler` was missing. If you install 4.1+ it should be fine.

**Comment by AdriwanKenoby** [comment]
Thanks a lot @jonnnnyw,

You have made a great tool. I removed the jerome-breton's installer, can't resolve dependencies.

I have a question, if u have time ?

In the doc, it is describe how to use custom request parameters in my js script.
In otherway i would like to had custom variable, like the time reponse. For example i want to make my own procedure, something like loadspeed.js and store the time response in a property of the reponse object and acces it in php via a method, someting like getResponseTime(). 

Before, i used curl but i need some stuff of phantomjs like screenshot to generate report.

Thanks a lot.

P.S.

**Comment by jonnnnyw** [comment]
You should be able to do it in a similar way to the request.

Create a custom response class:

```
    use JonnyW\PhantomJs\Message\Response;
    
    class CustomResponse extends Response
    {
        public $customField;
    
        public function getCustomField()
        {
            return $this->customField;
        }
    }
```

Then in your custom script just set the value in the response:

```
   response.customField = 'value';
```

Now when you make the request in the client, instead of passing in the default response instance you pass in your custom one:

```
    use JonnyW\PhantomJs\Client;
    
    $client = Client::getInstance();
    
    $request  = $client->getMessageFactory()->createRequest();
    $request->setMethod('GET');
    $request->setUrl('http://www.google.com');
    
    $response = new CustomResponse();
    
    $client->send($request, $response);
```

The trickiest part is where to put the `response.customField = 'value'` in your custom script. The `page_open.partial` might be the best place but remember that the procedure execute command could be delayed in a `window.setTimeout` if a delay is set so make sure you handle that. I guess it depends on what information you want to capture as to where you put it.

The code above hasn't been tested but it should work as described.
