### ISSUE TITLE
Not saving output file on capture request

### ISSUE THREAD

**Issue by carbontwelve** [jonnnnyw/php-phantomjs#109]
I am using the following code, and the var dump is showing a 200 and I can also var_dump body content, but its not saving the picture capture to disk. `$outputPath` is an absolute path e.g. `F:\tests\output\screengrab_3.jpg`

I am running on windows in Laravel 5.1.

``` php
$client = Client::getInstance();
$client->getEngine()->setPath( base_path('bin/phantomjs.exe') );
$client->isLazy();

/** @var \JonnyW\PhantomJs\Http\CaptureRequest $request */
$request  = $client->getMessageFactory()->createCaptureRequest($url);
$response = $client->getMessageFactory()->createResponse();

$request->setMethod('GET');

// @todo make commandline option default 5000
$request->setTimeout(5000);

$request->setOutputFile($outputPath);

$client->send($request, $response);

var_dump($response->getStatus());
```

**Comment by SalocinDotTEN** [comment]
Hi.

We are also using this as a standalone PHP CLI cron operated script that reads a list of websites from a JSON file.

We have also experienced the same issue but with only **ONE** website.
We tried setting the timeout longer although apparently it still does not work. We think that the script was not given enough time to generate the image.

**Comment by jonnnnyw** [comment]
There was feature added recently that lets you wait until all of the page resources have loaded before capturing the page.

[Documentation](http://jonnnnyw.github.io/php-phantomjs/4.0/3-usage/#on-load-finished)

Give it a try and let me know if it helps.

**Comment by SalocinDotTEN** [comment]
Hi,

Thanks.

Will try that if there are still complaints from my management of no image attachments.
