### ISSUE TITLE
Does not work on PHP 5.4.36

### ISSUE THREAD

**Issue by shivanraptor** [jonnnnyw/php-phantomjs#112]
I'm using PHP 5.4.36, it said: 

> Parse error:  syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) in /path/to/myproject/vendor/symfony/dependency-injection/ContainerBuilder.php on line 436

Seems that the dependency Symfony requires PHP 5.5+

**Comment by jonnnnyw** [comment]
Thanks for pointing this out. The tests are passing for PHP 5.3 and PHP 5.4 so I'm not sure why this would be throwing something up. Unless it's a Symfony update. 

Is this being used in an existing Symfony project?
