### ISSUE TITLE
Manually set content

### ISSUE THREAD

**Issue by omanizer** [jonnnnyw/php-phantomjs#114]
There are instances where I already have the HTML I need to display rather than requesting it from a URL.  It would be nice to have an easy way to use the setContent method existing in PhantomJS` API.  It looks like I could do this with a custom proc, but this seems like a common enough situation that it could warrant it's own method.

**Comment by jonnnnyw** [comment]
I believe this is the same request as https://github.com/jonnnnyw/php-phantomjs/issues/88.

I am currently working on this.
