### ISSUE TITLE
Specify width only?

### ISSUE THREAD

**Issue by kevinquillen** [jonnnnyw/php-phantomjs#115]
Is there a way to set the viewport width only and have the height not be required?

**Comment by jonnnnyw** [comment]
I haven't tested this scenario. Have you tried passing in an empty string as the height parameter?

**Comment by kevinquillen** [comment]
Yeah, when I did that it crashed out / never responds. Oddly, I wound up having to restart Apache.

**Comment by jonnnnyw** [comment]
It doesn't look like that this is possible according to the [docs](http://phantomjs.org/api/webpage/property/viewport-size.html).

> You must include height for this to work.

I tried a few different things to see if I could work around it but no joy. I don't think I will be able to support this until PhantomJS does.
