### ISSUE TITLE
getEngine()->setPath doesn't work on server 

### ISSUE THREAD

**Issue by farazirfan47** [jonnnnyw/php-phantomjs#125]
Here is my code for setting path `$client->getEngine()->setPath('..\\bin\\phantomjs.exe');`

Its working fine on local host but when I uploaded it to server that gives 

Fatal error: Uncaught exception 'JonnyW\PhantomJs\Exception\InvalidExecutableException' with message 'File does not exist or is not executable: ..\bin\phantomjs.exe' in /home/pricenz/public_html/vendor/jonnyw/php-phantomjs/src/JonnyW/PhantomJs/Engine.php:216 Stack trace: #0 /home/pricenz/public_html/vendor/jonnyw/php-phantomjs/src/JonnyW/PhantomJs/Engine.php(94): JonnyW\PhantomJs\Engine->validateExecutable('..\bin\phantomj...') #1 /home/pricenz/public_html/user/monitor.php(59): JonnyW\PhantomJs\Engine->setPath('..\bin\phantomj...') #2 {main} thrown in /home/pricenz/public_html/vendor/jonnyw/php-phantomjs/src/JonnyW/PhantomJs/Engine.php on line 216

Thanks

**Comment by lucl22** [comment]
Hi,
Some time, the problem comes from relative path. Try to set an absolute link like "/home/yourhostname/public_html/bin/phantomjs" and phantomjs permission(chmod) must be set to 0775. Also, executable (.exe) don't work with Linux hosting.

Hope that helps.
