### ISSUE TITLE
How can I set image repeating as repeating header?

### ISSUE THREAD

**Issue by baimurzin** [jonnnnyw/php-phantomjs#132]
I tried something like: 

```
   ` $request->setRepeatingHeader('<img src="http://site.com/img/logo.png"/>');`
```

But got nothing. Just a empty 1cm space at the header of page.

**Comment by jonnnnyw** [comment]
So after some investigation this seems to be an existing issue with PhantomJS - https://github.com/ariya/phantomjs/issues/12887.

The reason for this is that the header and footer are loaded separately from the main content so they do not use the same rules when it comes to waiting for resources to load. I tried to figure out a solution and the only way I can get this to work is to include the image you want to use in the main body of the page. Set it to `display: none;` and then use the same URL in your img tag for your repeating header. This essentially preloads your image before using it in the footer.

If the content you are loading isn't yours i.e. you don't have the ability to edit it, you may want to host your own page that loads the content in an iframe.
