### ISSUE TITLE
php-phantomjs don't work in iframes

### ISSUE THREAD

**Issue by juuh0123** [jonnnnyw/php-phantomjs#134]
My code:

` <?php

```
 error_reporting(E_ALL);
 ini_set("display_errors", true);
require '/var/www/html/vendor/autoload.php';

use JonnyW\PhantomJs\Client;

$client = Client::getInstance();
$client->getEngine()->setPath('/usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs');

$request  = $client->getMessageFactory()->createCaptureRequest('http://MyURL/src/index.html');

$response = $client->getMessageFactory()->createResponse();

$file = '/var/www/html/public/image/FOTO.jpg';

$request->setOutputFile($file);

$client->send($request, $response);
```

?>    `

HTML font: `<iframe src="https://MyIP/elasticsearch/#/dashboard/Akamai?embed&_g=(refreshInterval:(display:Off,pause:!f,section:0,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(filters:!(),panels:!((col:1,id:Akamai_edge_bandwidth,row:1,size_x:6,size_y:3,type:visualization),(col:7,id:Akamai_edge_request,row:4,size_x:6,size_y:3,type:visualization),(col:7,id:Akamai_origin_bandwidth,row:1,size_x:6,size_y:3,type:visualization),(col:1,id:Akamai_origin_request,row:4,size_x:6,size_y:3,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:akamai)),title:Akamai)" height="95%" width="100%"></iframe>`

Wrong image link: http://ap.imagensbrasil.org/image/parGTj

Image as it should be: http://ap.imagensbrasil.org/image/parYAW

Image.png (with error) : http://ap.imagensbrasil.org/image/pa4f2X

Tks

OBS: I've tried this: $request->setDelay(20); and it did not work

**Comment by jonnnnyw** [comment]
I have run some tests using a test page I set up (http://jonnyw.kiwi/tests/test-iframe.php) and the image is rendered with the iframe content.

Try setting the client to lazy load content:
  
```
$client = Client::getInstance();
$client->isLazy(); // Tells the client to wait for all resources before rendering

$request  = $client->getMessageFactory()->createRequest();
$request->setTimeout(5000); // Will render page if this timeout is reached and resources haven't finished loading
```

**Comment by StasToken** [comment]
**jonnnnyw** url: http://jonnyw.kiwi/tests/test-iframe.php broken please update it
