### ISSUE TITLE
contributing to the docs

### ISSUE THREAD

**Issue by hansvn** [jonnnnyw/php-phantomjs#135]
Is there anyway users can contribute to the [documentation](http://jonnnnyw.github.io/php-phantomjs)?

**Comment by jonnnnyw** [comment]
Yep. Fork the 'gh-pages' branch and then submit a pull request.

**Comment by hansvn** [comment]
How would I contribute to the docs then?
Do I just update the markdown version or do I also compile the html for the _site entities?

**Comment by jonnnnyw** [comment]
Just update the markdown. Github compiles it when the pull request is merged.
