### ISSUE TITLE
301 request error

### ISSUE THREAD

**Issue by ruslanbakanov** [jonnnnyw/php-phantomjs#138]
I used documentation example code from http://jonnnnyw.github.io/php-phantomjs/4.0/3-usage/
and got a 301 error after request

$request = $client->getMessageFactory()->createRequest('http://facebook.com', 'GET');

Please, help!
I don't know what is't means and don't find any information about this one

System:

cat /etc/oracle-release
Oracle Linux Server release 6.6

composer require "jonnyw/php-phantomjs:4.*"
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
 - Installing twig/twig (v1.27.0)
   Downloading: 100%

 - Installing symfony/yaml (v3.1.6)
   Downloading: 100%

 - Installing symfony/filesystem (v3.1.6)
   Downloading: 100%

 - Installing symfony/dependency-injection (v3.1.6)
   Downloading: 100%

 - Installing symfony/config (v3.1.6)
   Downloading: 100%

 - Installing jakoch/phantomjs-installer (2.1.1)
   Downloading: 100%

 - Installing jonnyw/php-phantomjs (v4.5.1)
   Downloading: 100%
 phantomjs -v
2.1.1

php -v
PHP 5.6.7 (cli) (built: Aug 15 2016 16:15:06)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by jonnnnyw** [comment]
A 301 means you are being redirected from facebook.com. I would imagine it is redirecting you from http://facebook.com to **https**://facebook.com. Try using https.

**Comment by ruslanbakanov** [comment]
Thank you for your answer! :)
I'm sorry. 
My bad...
Actually i get #301 error not only for facebook.com but also for any other link with http:// or https://
I added http:// and still have the same error code.

**Comment by jonnnnyw** [comment]
Can you dump out the response? What URL is it trying to redirect you to?
