### ISSUE TITLE
The chart split into two part when overflowed in PDF

### ISSUE THREAD

**Issue by BigJoyce** [jonnnnyw/php-phantomjs#141]
I have problem with page break. 
when a chart (I used Echarts)  in the end of the page,but overflowed, it will be split in another page.
The chart split into two part.

How can I avoid this case.

**Comment by jonnnnyw** [comment]
You can set the paper size which should do it.

```
$client = Client::getInstance();
   
$width  = '10cm';
$height = '20cm';

$request  = $client->getMessageFactory()->createPdfRequest();
$request->setPaperSize($width, $height);
```

**Comment by BigJoyce** [comment]
Very appreciate your response, 
when only one page, it worked,
but sometimes I don't know when the content overflowed,  hard to find a proper size for various page.
Thank you all the same.
