### ISSUE TITLE
Can't find phantomjs or execute phantomjs

### ISSUE THREAD

**Issue by rluisr** [jonnnnyw/php-phantomjs#142]
## Overview
My PHP Code says error occurred.
```
PHP Fatal error:  Uncaught JonnyW\PhantomJs\Exception\ProcedureFailedException: Error when executing PhantomJs procedure - File does not exist or is not executable: bin/phantomjs in /mnt/smbSSD_128GB/WebStorm/test-phantomjs/vendor/jonnyw/php-phantomjs/src/JonnyW/PhantomJs/Procedure/Procedure.php:138
Stack trace:
#0 /mnt/smbSSD_128GB/WebStorm/test-phantomjs/vendor/jonnyw/php-phantomjs/src/JonnyW/PhantomJs/Procedure/ProcedureValidator.php(84): JonnyW\PhantomJs\Procedure\Procedure->run(Object(JonnyW\PhantomJs\Procedure\Input), Object(JonnyW\PhantomJs\Procedure\Output))
#1 /mnt/smbSSD_128GB/WebStorm/test-phantomjs/vendor/jonnyw/php-phantomjs/src/JonnyW/PhantomJs/Procedure/ProcedureValidator.php(61): JonnyW\PhantomJs\Procedure\ProcedureValidator->validateSyntax('\n\n/**\n * Set up...')
#2 /mnt/smbSSD_128GB/WebStorm/test-phantomjs/vendor/jonnyw/php-phantomjs/src/JonnyW/PhantomJs/Procedure/ProcedureCompiler.php(107): JonnyW\PhantomJs\Procedure\ProcedureValidator->validate('\n\n/**\n * Set up...')
#3 /mnt/smbSSD_128GB/WebStorm/test-ph in /mnt/smbSSD_128GB/WebStorm/test-phantomjs/vendor/jonnyw/php-phantomjs/src/JonnyW/PhantomJs/Procedure/Procedure.php on line 138
```

## Code
```PHP
<?php
require_once 'vendor/autoload.php';

use JonnyW\PhantomJs\Client;

$client = Client::getInstance();

$request = $client->getMessageFactory()->createRequest('http://jonnyw.me', 'GET');
$response = $client->getMessageFactory()->createResponse();

$client->send($request, $response);

if ($response->getStatus() === 200) {
    echo $response->getContent();
}
```

## Tree
```
.
├── bin
│   └── phantomjs [chmod 777]
├── composer.json
├── composer.lock
├── test.php
└── vendor
    ├── autoload.php
    ├── composer
    ├── jakoch
    ├── jonnyw
    ├── symfony
    └── twig
```

## Version
PHP 7.1.0RC6 (cli) (built: Nov  9 2016 09:51:59) ( NTS )
php-phantomjs latest

Why this php code doesn't work?

**Comment by jonnnnyw** [comment]
Try setting an absolute path to your PhantomJS executable.

```
$client = Client::getInstance();
$client->getEngine()->setPath('/path/to/phantomjs');
```

If that doesn't work then try installing PhantomJS manually - http://phantomjs.org/download.html

**Comment by rluisr** [comment]
@jonnnnyw Sorry for the late reply.
Thanks reply and solve this problem.

**Comment by jakoch** [comment]
1. update to `"jakoch/phantomjs-installer": "2.1.1-p08"`, see patch https://github.com/jonnnnyw/php-phantomjs/pull/149
2. use helper class PhantomBinary - https://github.com/jakoch/phantomjs-installer#phantombinary,
    see patch https://github.com/jonnnnyw/php-phantomjs/pull/155

**Comment by jonnnnyw** [comment]
Have merged this in. Just running tests and will be released in v6.0.

**Comment by yuseferi** [comment]
The following codes will help you to fix the problem: 
- on windows: 
`$client->getEngine()->setPath(dirname(__FILE__).'/bin/phantomjs.exe');`

- on mac and Linux
`$client->getEngine()->setPath(dirname(__FILE__).'/bin/phantomjs');`

these helped me to fix the issue.

**Comment by AryaRDI** [comment]
hi

i'm getting this error on CentOS 7 and non of them fixed it i don't know what is wrong whit it. Whe i run it by terminal it is fine but when i run on the webservice it gives me the error.

`    <?php



    require 'vendor/autoload.php';
    use JonnyW\PhantomJs\Client;


try {

    $client = Client::getInstance();
    $client->getEngine()->setPath('/var/www/html/meteos/bin/phantomjs');
`

do have any suggestion ?

**Comment by salvatorecapolupo** [comment]
if you are using Composer, you can fix this error using this code line:

`$client->getEngine()->setPath('vendor/bin/phantomjs');`
