### ISSUE TITLE
composer: timeout on installing a dependencies package

### ISSUE THREAD

**Issue by goplastic** [jonnnnyw/php-phantomjs#144]
Hi, I am trying to install php phantomjs in my centos server using composer. 
It starts good but then it stops installing the package phantomjs. 
See screenshot. 
Any ideas on why it stops there?

Screenshot link: https://i.stack.imgur.com/aGLLe.png

**Comment by jonnnnyw** [comment]
It could be an intermittent issue with BitBucket (where the compiled PhantomJS executables are hosted). Can you confirm that you are still having this issue.

**Comment by amustill** [comment]
@jonnnnyw I am still seeing this issue as of today.

**Comment by jakoch** [comment]
- this is probably an upstream with `jakoch/phantomjs-installer`
- please use a newer version of that package `"jakoch/phantomjs-installer": "2.1.1-p08"` and report back
- if the issue remains, please open a ticket over at the installer repo

**Comment by jonnnnyw** [comment]
I have merged the latest version of phantom JS installer in so I will close this issue.
