### ISSUE TITLE
RAM used from php-phantomjs

### ISSUE THREAD

**Issue by matteoraggi** [jonnnnyw/php-phantomjs#146]
Hi, fastcomet answered me that them shared hosting is compatible with php-phantomjs and that they can install it for me. I have 2gb ram. do you think that it is enough?

**Comment by jonnnnyw** [comment]
It will be enough for this PHP library but you might want to check the phantomjs website to see if they have any minimum requirements - http://phantomjs.org. This library is essentially a light weight wrapper for their software.

**Comment by matteoraggi** [comment]
Minimum ram for phantomjs is 4b of ram. 
Now on fastcomet I have 6cpu and 6gb of ram, but after few minutes they corrected the answer telling me that I need a vps and that I can't use phantomjs from the shared hosting.
