### ISSUE TITLE
Problem with Laravel

### ISSUE THREAD

**Issue by stefanzweifel** [jonnnnyw/php-phantomjs#16]
Hello there

I tried to implement php-phantomjs to my Vagrant Laravel 4.2 application.

First I got the common error `PhantomJs file does not exist or is not executable: bin/phantomjs`. So I added a custom path to an executable and fresh version of phantomJS with `$client->setPhantomJs('/path/to/bin/phantomjs');`.

However, when I execute one of your examples, nothing happens and when I echo out $response->getStatus I get the value 0.

Am I doing something completely wrong or how can I use the given phantomjs bin, which is delivered in your package (installed with composer)?

Thanks for any help.

**Comment by neorganic** [comment]
Anyone heard of anyone who has successfully got it to work on any laravel version and lived to talk about it ?

**Comment by stefanzweifel** [comment]
I'm successfully running PhantomJs in an app of mine. I think my main issue back then was, that I didn't recognize that I should should have passed an absolute path to the config.

You can finde my implementation [here](https://github.com/stefanzweifel/screeenly/blob/master/modules/Screeenly/Services/PhantomsJsBrowser.php).

**Comment by neorganic** [comment]
@stefanzweifel  I have an absolute path to my phantomjs,
`$client->getEngine()->setPath( base_path() . '/vendor/bin/phantomjs');`
^ which coresponds to /var/www/html/app.name/vendor/bin/phantomjs  , which in my scenario is correct. I have  "bin-dir": "vendor/bin" in my composer.json .
 With all this done I am, still having major issues. Currently stuck on infinite loading, when trying to get the site contents(one exception is with one primitive simple and small SPA that I own) that I am able to dump the contents, but even then the response code for that SPA is 0 .
my environment --> php 7.1 , Laravel 5.5 , ubuntu 16.04

@jonnnnyw The trouble shooting page is 404. I think you should reopen this issue, or I can submit a new one.

**Comment by neorganic** [comment]
**UPDATE**
Ok so after more testing the problem appears to be that some websites are being rendered and some are not.
for e.g. can anyone confirm that they can render the website https://consulte.in with phantomjs ?

**Comment by stefanzweifel** [comment]
@neorganic Works for me in my implementation. You could test it [here](http://screeenly.com/try).

**Comment by neorganic** [comment]
@stefanzweifel Great, but why is your implementation seems to not be able to process(take screenshots) of js-only websites? Like https://taxibambino.com  . This is very essential for me - one of the reasons I am doing R&D with phantomjs .

**Comment by stefanzweifel** [comment]
My server is in Frankfurt, Germany. Opening and downloading your site from Switzerland takes around ~4-5 seconds.
Maybe you have to look into the `delay` option?

I would also suggest checking out Google Chrome Headless. There's a great package you can use with Laravel: https://github.com/spatie/browsershot
(Chrome Headless is much more reliable than PhantomJs)
