### ISSUE TITLE
Execute js script when page loaded

### ISSUE THREAD

**Issue by helldude** [jonnnnyw/php-phantomjs#164]
Hello. How i can exucute script when page loaded? For exemple: Click on the button that opens a new page. Then get the code for this page

**Comment by Teaxtor** [comment]
I suggest using partial script injection, have a look here:
http://jonnnnyw.github.io/php-phantomjs/4.0/4-custom-scripts/

You would want to create a page_open.partial script

**Comment by jonnnnyw** [comment]
Thanks @Teaxtor
