### ISSUE TITLE
QXcbConnection: Could not connect to display  PhantomJS has crashed.

### ISSUE THREAD

**Issue by 326956600** [jonnnnyw/php-phantomjs#167]
I run it under php cli mode successflu. But, when i run it with http mode.This error log showed.

Which version of PhantomJS are you using?
Version 2.1.1

Which version of PHP are you using?
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )

Which operating system are you using?
Ubuntu 16.04 LTS

Which version of php-phantomjs are you using?
"jonnyw/php-phantomjs": "4.*"

What steps will reproduce the problem?
put project to localhost dir
run it by browser
type  http://localhost/php-phantomjs/test.php
Press enter

Which version of browser are you using?
chrome 56.0.2924.87 (64-bit)

**Comment by 326956600** [comment]
Here is my code
```php
require 'vendor/autoload.php';
use JonnyW\PhantomJs\Client;

$client = Client::getInstance();
$client->getEngine()->setPath('/usr/lib/phantomjs/phantomjs');
//$client->getEngine()->debug(true);
$request = $client->getMessageFactory()->createRequest('http://jonnnnyw.github.io/php-phantomjs/4.0/6-debugging/', 'GET');

/**
 * @see JonnyW\PhantomJs\Http\Response
 **/
$response = $client->getMessageFactory()->createResponse();
// Send the request
$client->send($request, $response);

var_dump($response->getContent());
```

**Comment by 326956600** [comment]
i solved this problem
[](http://darkwind.cc/Blog/front/article.html?id=74)

**Comment by 326956600** [comment]
i solved this problem

[http://darkwind.cc/Blog/front/article.html?id=74](url)

**Comment by karolisg** [comment]
@dark-wind Can you share how did you fixed it? Link is not working

**Comment by dark-wind** [comment]
@karolisg sorry,i moved my blog
here is my solution:
i got the way from this url: [https://github.com/ariya/phantomjs/issues/14061](url)

i add this parameter for it

`
QT_QPA_PLATFORM=offscreen
`

run it with 
`sudo -u www-data QT_QPA_PLATFORM=offscreenphantomjs`

here is a shell to run with parameter

`
#!/bin/sh

LD_LIBRARY_PATH="/usr/lib/phantomjs:$LD_LIBRARY_PATH"

export LD_LIBRARY_PATH

export QT_QPA_PLATFORM=offscreen

exec "/usr/lib/phantomjs/phantomjs" "$@"
`
