### ISSUE TITLE
Is there any way I can generate a screenshot using an HTML string or local file via filepath?

### ISSUE THREAD

**Issue by bbapp** [jonnnnyw/php-phantomjs#170]
I want to create screenshots without requiring a URL.

**Comment by jonnnnyw** [comment]
This is coming in V5. I've been working on it but am stacked with work at the moment. I've been promising it for a while but it's not far off.

**Comment by jonnnnyw** [comment]
Duplicates https://github.com/jonnnnyw/php-phantomjs/issues/88
