### ISSUE TITLE
NotWritableException

### ISSUE THREAD

**Issue by moe-m** [jonnnnyw/php-phantomjs#18]
myself, and another user have the same issue:

http://stackoverflow.com/questions/25098733/php-phantomjs-on-wamp-server-fatal-error-uncaught-exception/25128987#25128987

I'm running on windows(easyphp). Other commands in my project can write to the system temp dir. Not sure why this cannot. See the stackoverflow for my temporary solution.

**Comment by ahmadseder** [comment]
Still I see the problem and the solutions is not working

**Comment by MishDish** [comment]
Hello , 

Please can you help me !  I'm using php-phantomJs on Wamp, i installed all dependencies properly  lin the  documentation description  , but when i exceute the file is throwing  2 fatal errors : 
Fatal error: Uncaught exception 'JonnyW\PhantomJs\Exception\ProcedureFailedException' with message 'Error when executing PhantomJs procedure - File does not exist or is not executable: bin/phantomjs' in C:\wamp\www\php-phantomjs-master\src\JonnyW\PhantomJs\Procedure\Procedure.php on line 137
( ! ) JonnyW\PhantomJs\Exception\ProcedureFailedException: Error when executing PhantomJs procedure - File does not exist or is not executable: bin/phantomjs in C:\wamp\www\php-phantomjs-master\src\JonnyW\PhantomJs\Procedure\Procedure.php on line 137  .

I'm suspecting if it's  issue with backslash and forward slash but i don't know where in the code should be corrected in order  to read and excetue phantomJs.exe .

Thank you !
