### ISSUE TITLE
ProcedureFailedException

### ISSUE THREAD

**Issue by moe-m** [jonnnnyw/php-phantomjs#19]
Fatal error: Uncaught exception 'JonnyW\PhantomJs\Exception\ProcedureFailedException' with message 'Error when executing PhantomJs procedure "default" - File does not exist or is not executable: bin/phantomjs' 

I followed the instructions and manually created my bin folder in the project root. phantomjs.exe, phantomloader, and phantomloader.bat were installed successfully. Not sure why this cannot execute. In your previous version I remember manually changing the location from phantomjs to phantomjs.exe in client.php to work with Wndows. Manually setting $client->setBinDir in examples/basic-request.php results in the same error.

**Comment by perochak** [comment]
Faced same issue.

Fixed it using following code

$client->getEngine()->setPath(dirname(__FILE__).'/bin/phantomjs.exe');

**Comment by zhilevan** [comment]
This 

`$client->getEngine()->setPath(dirname(__FILE__).'/bin/phantomjs.exe');`

fix the issue for me.
