### ISSUE TITLE
How to capture only canvas on page to png image ?

### ISSUE THREAD

**Issue by crouti** [jonnnnyw/php-phantomjs#200]
Hi, i use the createCaptureRequest method to convert web page to png image, but i only would like to retrieve a particular canvas on the page and convert it to png.
Can i "clean" the webpage before capturing ?
Is this possible ? Can you please help ?
Thanks

**Comment by LiamMcArthur** [comment]
I'd look at combining this with [DOMXPath](http://php.net/manual/en/class.domxpath.php) to get the particular elements you need from the page before converting it.

**Comment by crouti** [comment]
Thanks @LiamMcArthur !
Solution came using CasperJS embedded into a PHP plugin : https://github.com/alwex/php-casperjs
