### ISSUE TITLE
How can I change the user-agent?

### ISSUE THREAD

**Issue by LiamMcArthur** [jonnnnyw/php-phantomjs#208]
Is it possible to change the user-agent? I'm trying to change it like this:

`$request->addSetting('userAgent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063';`

Unfortunately, this isn't working. It's still returning the current Chrome 60 user-agent.

**Comment by LiamMcArthur** [comment]
This can be ignored, I appear to have managed to get it working!

**Comment by ConsultJL** [comment]
@LiamMcArthur How were you able to do that?

**Comment by LiamMcArthur** [comment]
Here's how I randomized the user agent:

```
/*
 Create some user-agents
*/
$chrome_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36';
$firefox_agent = 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0';
$ie_agent = 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko';
$edge_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063';

/*
* Now randomize the user-agent
*/
$agents = array($chrome_agent, $firefox_agent, $edge_agent, $ie_agent);
$user_agent = array_rand(array_flip($agents));
$request->addSetting('userAgent', $user_agent);
```

**Comment by DmitriyJaver** [comment]
> $request->addSetting('userAgent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063');
- it really helped me, thanks!
