### ISSUE TITLE
Problems with executing in windows environment

### ISSUE THREAD

**Issue by kenyiu** [jonnnnyw/php-phantomjs#22]
Hello,

I encountered an error when executing my codes in XAMPP (Windows) enviornment, while there was no error at all on my ubuntu.

The error was like this: 

```
Uncaught exception 'JonnyW\PhantomJs\Exception\ProcedureFailedException' with message 'Error when executing PhantomJs procedure "default" - File does not exist or is not executable: 

C:/xampp/htdocs/phantom/bin/phantomloader' in C:\xampp\htdocs\phantom\vendor\jonnyw\php-phantomjs\src\JonnyW\PhantomJs\Procedure\Procedure.php:132 Stack trace: #0 

C:\xampp\htdocs\phantom\vendor\jonnyw\php-phantomjs\src\JonnyW\PhantomJs\Client.php(171): JonnyW\PhantomJs\Procedure\Procedure->run(Object(JonnyW\PhantomJs\Client), Object(JonnyW\PhantomJs\Message\Request), Object(JonnyW\PhantomJs\Message\Response)) #1 

C:\xampp\htdocs\phantom\functions_new.php(20): JonnyW\PhantomJs\Client->send(Object(JonnyW\PhantomJs\Message\Request), Object(JonnyW\PhantomJs\Message\Response)) #2 C:\xampp\htdocs\phantom\oneitem_ky.php(174): argos('012/803') #3 {main} thrown in C:\xampp\htdocs\phantom\vendor\jonnyw\php-phantomjs\src\JonnyW\PhantomJs\Procedure\Procedure.php on line 132
```

What I did:
1. Used composer to install the dependencies
2. Changed Client.php under vender\jonnyw\php-phantomjs\src\JonnyW\PhantomJs line 110, the value of $this->phantomJs = 'C:/xampp/htdocs/phantom/bin/phantomjs.exe';
3. Changed  Client.php under vender\jonnyw\php-phantomjs\src\JonnyW\PhantomJs line 111, the value of $this->phantomLoader = 'C:/xampp/htdocs/phantom/bin/phantomloader';

I also tried changing $this->phantomLoader = 'C:/xampp/htdocs/phantom/bin/phantomloader.bat', but still did not work out.

Any ideas?

Thanks.

**Comment by andersalm** [comment]
I also face a problem executing the files with WAMP 2.5 and Windows 8.1.

"Fatal error: Uncaught exception 'JonnyW\PhantomJs\Exception\ProcedureFailedException' with message 'Error when executing PhantomJs procedure "capture" - File does not exist or is not executable: bin/phantomjs'"

When I add...
	$client->setBinDir('bin/');
	$client->setPhantomJs('bin/phantomjs.exe');
...it stops at

Fatal error: Uncaught exception 'JonnyW\PhantomJs\Exception\InvalidExecutableException' with message 'File does not exist or is not executable: bin/phantomloader'

It wont help to add 
	$client->setPhantomLoader('bin/phantomloader');
or
	$client->setPhantomLoader('bin/phantomloader.bat');

I also tried absolute path with forward and backslash with same result.
I really need this to work with php.

**Comment by majamusan** [comment]
i am having the same issue with 3.* and laravel 5 on an ubuntu system

**Comment by andersalm** [comment]
I dont know if this is appropriate, but my workaround was using another repository with a few minor modifications: https://github.com/microweber/screen

**Comment by MishDish** [comment]
Hello , is the issue with executing  phantomJs on Wamp solved ?  I have the same problem : 
On execution   is throwing 2 fatal errors : 
Fatal error: Uncaught exception 'JonnyW\PhantomJs\Exception\ProcedureFailedException' with message 'Error when executing PhantomJs procedure - File does not exist or is not executable: bin/phantomjs' in C:\wamp\www\php-phantomjs-master\src\JonnyW\PhantomJs\Procedure\Procedure.php on line 137
( ! ) JonnyW\PhantomJs\Exception\ProcedureFailedException: Error when executing PhantomJs procedure - File does not exist or is not executable: bin/phantomjs in C:\wamp\www\php-phantomjs-master\src\JonnyW\PhantomJs\Procedure\Procedure.php on line 137 .

Thank you !

**Comment by k1ng440** [comment]
Sadly bad no. You can edit a line to fix this. The developer seems has no intention to fix this issue

**Comment by haffoudhi** [comment]
try this one on windows:
# vendor/../PhantomJs/Client.php
update getCommand() to 
public function getCommand()
    {
        $phantomJs     = $this->getPhantomJs();
        $phantomLoader = $this->getPhantomLoader();

        $this->validateExecutable($phantomJs);
        
        $options = $this->getOptions();

        if ($this->debug) {
            array_push($options, '--debug=true');
        }

        return sprintf('%s %s', $phantomJs, implode(' ', $options)); // deleted phantomloader part
    }

# Your test.php file
require_once('vendor/autoload.php');//make sure this path is correct
use JonnyW\PhantomJs\Client;

$client = Client::getInstance();
$client->setPhantomJs(__DIR__.'/bin/phantomjs.exe'); // __DIR__ is needed

**Comment by jawadrepo** [comment]
I have Fixed this issue
I am using WAMP , on windows 7 and symfony2.  I just kept on getting 
 "File does not exist or is not executable ..... "

So here is what you need to do

goto: vendor\jonnyw\php-phantomjs\src\JonnyW\PhantomJs\Client.php

        $this->binDir          = '';
        $this->phantomJs  = 'C:\wamp\www\alpha\bin\phantomjs.exe';
        $this->phantomLoader   = '%s/phantomloader';
public function __construct(ProcedureLoaderInterface $procedureLoader, MessageFactoryInterface $messageFactory)
    {
        $this->procedureLoader = $procedureLoader;
        $this->messageFactory  = $messageFactory;
        $this->binDir          = '';
        $this->phantomJs  = 'C:\wamp\www\alpha\bin\phantomjs.exe';
        $this->phantomLoader   = 'C:\wamp\www\alpha\vendor\jonnyw\php-phantomjs\bin\phantomloader';
    }

The thing is that if I dont put an (exe) after phantomjs the is_executable function fails which throws this exception. as for the phantomloader file i just defined the complete path without extention.


Next you need to go to the function getCommand() its in the same file and comment the part where it says [ $this->validateExecutable($phantomLoader); ] .
Comment the above statement.
 
Last what I did was goto file 
vendor\jonnyw\php-phantomjs\src\JonnyW\PhantomJs\DependencyInjection\ServiceContainer.php

this is the default path where it saves the file so you can change it according to your needs.
$this->setParameter('phantomjs.cache_dir' , sys_get_temp_dir());
which means your file is saved at [ C:\windows\TEMP ]
I changed it to 
$this->setParameter('phantomjs.cache_dir', 'C:\wamp\www\alpha\vendor\jonnyw\php-phantomjs\cache');

So the file stays in my source code , you can place it anywhere you want.

This is how it worked for me.

**Comment by efsjouw** [comment]
The solution haffoudhi posted works for me.

**Comment by agungsb** [comment]
The solution haffoudhi posted seems to work for me too. But, everytime I run the application, the following error appears:

Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\PhpPhantom\vendor\jonnyw\php-phantomjs\src\JonnyW\PhantomJs\Procedure\Procedure.php on line 107

If I trace the code, the execution error belongs to:

$result = stream_get_contents($pipes[1]);

Any thoughts? Thanks.. :)

**Comment by haffoudhi** [comment]
this is a php error, the max execution time of php scripts in your server is 30 seconds. You need to extend this limit: add this line at the start of php script: set_time_limit(60); in order to extend the limit to 60s, you can change 60 if you need more time.

PS: put this line in your php script, where you are calling phantomjs.

**Comment by PetrToman** [comment]
This is a pretty straightforward bug, that can be fixed easily. With composer, you can use the following workaround (on Windows) in the meantime:

```
$client = Client::getInstance();
$client->getEngine()->setPath(__DIR__ . '\bin\phantomjs.exe');
```

**Comment by kybarg** [comment]
This works for me
```
$client = Client::getInstance();
$client->getEngine()->setPath('..\\bin\\phantomjs.exe');
```

OR

```
$client = Client::getInstance();
$client->getEngine()->setPath('.\\bin\\phantomjs.exe');
```

**Comment by jonnnnyw** [comment]
I am going to assume this issue has been resolved. If you have any further problems open up another issue and I will take a closer look.

**Comment by zhilevan** [comment]
This 

`$client->getEngine()->setPath(dirname(__FILE__).'/bin/phantomjs.exe');`

fix the issue for me.

**Comment by abdulhadad** [comment]
Using Windows 10.0.15063, xampp 7.1.4 w/ phantomjs-2.1.1 doesn't work, but when using phantomjs-1.9.8 it's works. 

This code for both linux and windows:
if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
    $client->getEngine()->setPath(dirname(__FILE__).'/bin/phantomjs.exe');
}

**Comment by NabiKAZ** [comment]
One question.

This works:
```
$client->getEngine()->setPath('c:\foo\bar\phantomjs.exe');
```

But when I have `c:\foo\bar\` in the PATH system. How can use it?

I try these but don't works:
```
$client->getEngine()->setPath('phantomjs.exe');
$client->getEngine()->setPath('.\phantomjs.exe');
$client->getEngine()->setPath('./phantomjs.exe');
```

**Comment by Sensetivity** [comment]
I have same issue. I need set full path to phantomjs.exe file.
