### ISSUE TITLE
DependencyInjection Error!

### ISSUE THREAD

**Issue by Lukasss93** [jonnnnyw/php-phantomjs#222]
Today I launched composer update command, automatically updating symfony/dependency-injection from v3.3.9 to v3.4.0

Now I got this error:
Declaration of JonnyW\PhantomJs\DependencyInjection\ServiceContainer::load() should be compatible with Symfony\Component\DependencyInjection\Container::load($file)

I've fixed this error adding "symfony/dependency-injection":"3.3.9" to composer.json file.

Please fix it.

**Comment by yetaai** [comment]
Thanks for sharing. Are you saying the composer.json file in project folder or vendor sub folder?

**Comment by Lukasss93** [comment]
@yetaai project folder
