### ISSUE TITLE
Laravel 4.2 Infinite loop

### ISSUE THREAD

**Issue by MrGutis** [jonnnnyw/php-phantomjs#26]
I am getting infinite loop when setting setBinDir and setPhantomJs. If I skip any of those I get complained of not finding path or not executable.

```
        $client = Client::getInstance();
        $client->setBinDir('/phantombin/');
        $client->setPhantomJs('/phantombin/');

        $client->debug(true); // Set debug flag

        $request  = $client->getMessageFactory()->createRequest('http://github.com');
        $request->setTimeout(5000);
        $response = $client->getMessageFactory()->createResponse();

        $client->send($request, $response);

        echo $client->getLog(); // Output log
```

**Comment by neorganic** [comment]
Using Laravel 5.5 . Also getting an infinite loop or when echo the log on very small, simple websites
```
   $client->getEngine()->debug(true);
        $client->send($request, $response);
        dd($client->getLog());
```
(dd is a die and dump function)
, ^ get the same as @MrGutis got in the terminal.

Call to undefined method JonnyW\PhantomJs\Client::setPhantomLoader()

`$client->setPhantomLoader('../vendor/jonnyw/php-phantomjs/bin/phantomloader');`
^ I am guessing this part is obsolete with the current version of php-phantomjs ?
