### ISSUE TITLE
Invalid method provided.

### ISSUE THREAD

**Issue by vaclav-cerny** [jonnnnyw/php-phantomjs#265]
Hello,

I'm trying to use PHP PhantomJS on Laravel framework. I followed official installation steps and I got an errors relating to `symfony/dependency-injection conflicts with symfony/console`. So I installed `@dev` version and it went well. But I'm still getting an error `Class PhantomInstaller\Installer is not autoloadable, can not call post-install-cmd script` and when I'm trying to run basic usage example then I'm also getting an error `Invalid method provided` on every PhantomJS method.

What can I do? Is there any way how to fix it or any other way to get web content through PHP?

Thanks for help.

**Comment by keetamhoang** [comment]
same issue here, any help?

**Comment by vaclav-cerny** [comment]
> same issue here, any help?

The solution was to use headless chrome instead.

**Comment by jpvdw86** [comment]
I had the same problem regarding the error "Invalid method provided". with the :@dev version.

In the bundle it seems that he expects the following variables "FactoryInterface" ->createRequest (<url>, <method>).
however, the naming is incorrect and must be ->createRequest(<method>, <url>). The annotations and variable are incorrectly named. Turn around the variables does work.
