### ISSUE TITLE
How can I used 'page.evaluate'

### ISSUE THREAD

**Issue by aiyuchen** [jonnnnyw/php-phantomjs#27]
I want to used like this
```
	page.evaluate(function() {
		var ev = document.createEvent('MouseEvents');

		ev.initEvent('click', true, true);
		document.querySelector('a[href="#Event_object"]').dispatchEvent(ev);
	});
```

**Comment by muzavan** [comment]
Hello @jonnnnyw ,

The URL is not valid anymore. Where I can find about how to write custom PhantomJS scripts?

**Comment by jonnnnyw** [comment]
Here you go: http://jonnnnyw.github.io/php-phantomjs/4.0/4-custom-scripts/
