### ISSUE TITLE
Request data not encoded issue

### ISSUE THREAD

**Issue by damonkreft** [jonnnnyw/php-phantomjs#29]
`urldecode()` is used after `http_build_query()`'ing the request data, producing unsafe non-encoded data with a high risk of malformed JS. The request data contains \ (backslash), ' (apostrophe), new line chars etc, the request breaks...

```javascript
page.open ('http://localhost:8889/charts', 'POST', 'testRequest=This breaks using this apostrophe ' plus this new line char 
 also, there should be a backslash in front of 	his', function (status) {
     ...
});
```

Removing `urldecode()` produces...

```javascript
page.open ('http://localhost:8889/charts', 'POST', 'testRequest=This+breaks+using+this+apostrophe+%27+plus+this+new+line+char+%0A+also%2C+there+should+be+a+backslash+in+front+of+%09his', function (status) {
    ...
});
```

which seemingly decodes fine on the server side.

Pull request https://github.com/jonnnnyw/php-phantomjs/pull/28

**Comment by jonnnnyw** [comment]
This has been fixed in v3.1.5.
