### ISSUE TITLE
console.log produces blank content response.

### ISSUE THREAD

**Issue by ThatOdieGuy** [jonnnnyw/php-phantomjs#32]
I've got the library working pretty well for my purposes. So thanks for this!

I did spend an extra long time trying to figure out why console.log wasn't working. Any time I called console.log(), PHP PhantomJS would return a blank response. After some debugging, I found that PHP PhantomJS returns the response as a JSON object through console.log. And the log through system.stderr.write

Is there a reason for this? Perhaps Windows or some OS doesn't properly do system.stderr? If not, I'd love to swap the two so that console.log works as it should. There's plenty of my own code as well as snippets I'd like to use which use console.log. Also, I'm sure other users out there are banging their heads against walls trying to figure out why a call to console.log completely breaks the script.

**Comment by jonnnnyw** [comment]
Version 4 no longer uses console.log
