### ISSUE TITLE
Overriding the createCaptureRequest procedure

### ISSUE THREAD

**Issue by daviestar** [jonnnnyw/php-phantomjs#34]
Hey

It would be good to be able to add a custom procedure to `createCaptureRequest` and override the default `capture.proc` with `setType()` like other `Request`s.

Cheers

**Comment by daviestar** [comment]
Hey

I'm back on this project again, and trying to figure out how to override your capture.proc properly instead of just overwriting it in the vendor folder.  I know very little about PHP, so please forgive my n00biness :)

Basically I need to create a custom phantomJS script for screen capture.  My `capture.proc` is tested and working, when working directly in the vendor folder, so all good there.

The problem starts when following [your example](http://jonnnnyw.github.io/php-phantomjs/advanced.html#using-custom-request-parameters-in-your-script) here.  I think because it shows how to override `createRequest` and not `createCaptureRequest` method.  My code (Laravel):

```
$serviceContainer = ServiceContainer::getInstance();
$procedureLoader = $serviceContainer->get('procedure_loader_factory')
    ->createProcedureLoader(app_path().'/LoyaltyReporting/Shot/procedures');

$client = Client::getInstance();
$client->debug(true);

$client->getProcedureLoader()->addLoader($procedureLoader);

$request = $client->getMessageFactory()->createRequest();
$request->setType('screenshot');

$request->setMethod('POST');
$request->setUrl($url);
$request->setCaptureFile(public_path().$image_path);
$request->setViewportSize(980, 650);
$request->setRequestData($post_data);

$response = $client->getMessageFactory()->createResponse();

$client->send($request, $response);
```
Error:
```
Call to undefined method JonnyW\PhantomJs\Message\Request::setCaptureFile()
```
Or changing to this:
```
$request = $client->getMessageFactory()->createCaptureRequest();
```
Error:
```
Call to undefined method JonnyW\PhantomJs\Message\CaptureRequest::setType()
```
Any help would be great.  Thanks again.

**Comment by jonnnnyw** [comment]
Version 4 now accepts custom types and also supports injecting and compiling procedures at runtime
