### ISSUE TITLE
Custom Procedure - returning data

### ISSUE THREAD

**Issue by mlisowski** [jonnnnyw/php-phantomjs#36]
Hi, 
I have a problem: I've created custom procedure - it is working fine, is doing all things as I am expected I just have no idea how to return any custom data to response object? 

Can you help me how to do it ? 

For example I have:

var result = {'status': true, 'something': false};

and now I would like to return it to response object so I can do something with that in PHP.

Thanks

**Comment by jonnnnyw** [comment]
This should do the trick:

console.log(JSON.stringify(response, undefined, 4));

Where response is the data you want to send back. After that your PHP $request object should contain all the data from response.
