### ISSUE TITLE
Missing require autoload in examples

### ISSUE THREAD

**Issue by nemesis13** [jonnnnyw/php-phantomjs#40]
Hi,

all official examples I've seen so far are missing

    require "vendor/autoload.php";

No examples worked for me without that. This requirement might be obvious for people used to composer, but certainly not to newbies.

Cheers
Hubert Grzeskowiak

**Comment by jonnnnyw** [comment]
The examples in repo contain an autoload include for reference. It is assumed your application handles the autoload.

**Comment by nemesis13** [comment]
I thought the examples are supposed to run standalone. The docs don't mention any specific setup. Also I don't think every PHP developer knows composer.

**Comment by budnail** [comment]
I ran into the same thing. Eventually figured it out.  Maybe make a note on the Usage page to help the next guy?
