### ISSUE TITLE
Cannot do request

### ISSUE THREAD

**Issue by CriztianiX** [jonnnnyw/php-phantomjs#41]
Hello... i have this code: 

```
    $client = Client::getInstance();

    $phantomjs = APP . 'bin' . DS . 'phantomjs';
    $phantomloader = APP . 'bin' . DS . 'phantomloader';

    $client->setPhantomJs($phantomjs);
    $client->setPhantomLoader($phantomloader);


    $request  = $client->getMessageFactory()->createRequest();
    $response = $client->getMessageFactory()->createResponse();

    $request->setMethod('GET');
    $request->setUrl('http://www.google.com');
    $client->send($request, $response);

    if($response->getStatus() === 200) {
        echo $response->getContent();
    }
```

But the response always contains: 

object(JonnyW\PhantomJs\Message\Response) {
    headers => array(
        'User-Agent' => 'Mozilla/5.0 (Unknown; Linux i686) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34',
        'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8'
    )
    status => (int) 408
    content => null
    contentType => null
    url => 'http://www.google.com/'
    redirectUrl => null
    time => '2014-12-19T19:58:08.646Z'
    console => array()
}

any idea?

**Comment by jonnnnyw** [comment]
That means your request to google.com is timing out. Is your server behind a firewall? Also, try changing the URL to something like ```http://example.com``` to see if it isn't Google blocking your connection.

**Comment by jonnnnyw** [comment]
Is this still an issue?

**Comment by sbouafif** [comment]
I just had the same issue.

I'm using a VM for this project, when tested php-phantomjs worked well on a local network but not on the Internet. I changed the ip of dns server on my VM (in /etc/resolv.conf in Ubuntu) to 8.8.8.8. And now everything is fine.

**Comment by pctin** [comment]
The same to me.

I see sometime it returns 408 status and real content, but also 408 and null content, here is my code:

        $client = JonnyW\PhantomJs\Client::getInstance();
        $client->setBinDir(__DIR__ . '/../../vendors/php-phantomjs/bin');
        $client->setPhantomJs(__DIR__ .  '/../../vendors/php-phantomjs/bin/phantomjs.exe');
        $client->setPhantomLoader(__DIR__ .  '/../../vendors/php-phantomjs/bin/phantomloader');
        // set sock5 proxy from TOR
        $client->addOption("--proxy=10.220.83.30:40099");
        $client->addOption('--proxy-type=socks5');
        // disable ssl
        $client->addOption('--ssl-protocol=any');

        $request  = $client->getMessageFactory()->createRequest("https://check.torproject.org");
        $response = $client->getMessageFactory()->createResponse();

        $client->send($request, $response);
        
        var_dump($response);die;

It's not stable. I'm using TOR with sock5 proxy. Some time it return content but sometime not.
@jonnnnyw you said the request time out, but is there option we can set time out in PHP API?

**Comment by jonnnnyw** [comment]
Version 4 has just been released which may fix this issue. I suspect it's the phantomloader script which has been removed in the new version. Try upgrading and see if this solves your problem.

**Comment by rpgroot** [comment]
i have this problem with php-phantomjs version 4, request status zero and blank page.
this problem not exist in version 3
