### ISSUE TITLE
The capture is not saved

### ISSUE THREAD

**Issue by rkmax** [jonnnnyw/php-phantomjs#43]
I've installed php-phantomjs like the documentation say and run the following example. the execution finish without errors but the file `'/home/rkmax/file.jpg'` never its created

```php
<?php

    use JonnyW\PhantomJs\Client;

    $client = Client::getInstance();

    /** 
     * @see JonnyW\PhantomJs\Message\CaptureRequest
     **/
    $request = $client->getMessageFactory()->createCaptureRequest('http://google.com', 'GET');
    $request->setCaptureFile('/home/rkmax/file.jpg');

    /** 
     * @see JonnyW\PhantomJs\Message\Response 
     **/
    $response = $client->getMessageFactory()->createResponse();

    // Send the request
    $client->send($request, $response);
```

I'm using PHP 5.6.4 nad phantomjs 3.1.4

**Comment by rkmax** [comment]
Somebody?

**Comment by jonnnnyw** [comment]
Can you make sure that your ```/home/rkmax/``` directory is writeable by your web server?

This is most likely an issue with write permissions.

**Comment by rkmax** [comment]
yeah @jonnnnyw i have correct permissions

**Comment by jonnnnyw** [comment]
Try setting 777 permissions on it as a test (I'd recommend reverting it back afterwards). Also try and screen capture a different URL and see what you come up with.

The tests for the capture are passing so my assumption is that it's something local to your system or the URL you are capturing.

**Comment by rkmax** [comment]
the capture works sometimes if add

```php
 $client->send($request, $response)->getContent();
```

**Comment by jonnnnyw** [comment]
` $client->send($request, $response)->getContent();` will have no influence on whether your capture works or not - it's a simple getter method.

**Comment by aoiserizawa** [comment]
do I still need to install something to make the capture work? its not also working on my local. @rkmax what did you do to make it work? TIA

**Comment by wwendorf** [comment]
Same here, no file is saved.

**Comment by rkmax** [comment]
@wwendorf  @jonnnnyw I just call getContent and just sometimes works it's like a 60/40 chances to work

**Comment by wwendorf** [comment]
It looks to me like the phantomjs executable can't be executed, or even set to be an executable.  I can't do a chmod 777 on it at all.

Just tried reinstalling with no luck, I even downloaded the binary tar file and put it in there with no luck.

Wade

**Comment by wwendorf** [comment]
I tried to use phantomjs -v to see the version, but it would not run.  I tried installing phantomjs via apt-get, which worked, and I am now able to get the version from it, however, even if I put a ln -s /usr/bin/phantomjs into the /vagrant/bin directory, it won't work and gives me the:

`sh: 1: /usr/bin: Permission denied`

error reported earlier.

Wade

**Comment by jonnnnyw** [comment]
Firstly, I would compile PhantomJS for your system. The compiled Linux executables are pretty generic so are not guaranteed to work. This seems to fix most peoples issue.

Regarding it working sometimes and not others, it could be that the page hasn't fully loaded when it takes the capture. Try adding a delay to see if that makes any difference:

http://jonnnnyw.github.io/php-phantomjs/4.0/usage/#delay-page-render

**Comment by jonnnnyw** [comment]
If it's a permissions error then you will need to give the user that is running the script (apache?) permission to access /usr/bin

**Comment by rkmax** [comment]
@jonnnnyw there's some way to listen for a render completed event?

**Comment by jonnnnyw** [comment]
@rkmax As far as I am aware there isn't anything native to PhantomJS to listen on that. There are some scripts around that claim to do it but they look pretty messy. I looked into it a while back with no success. I'll see if anything new has come about since.

**Comment by wwendorf** [comment]
I actually changed the ownership of the phantomjs exe to www-data and it still doesn't run.

**Comment by jonnnnyw** [comment]
@rkmax The latest release has a [feature](http://jonnnnyw.github.io/php-phantomjs/4.0/3-usage/#on-load-finished) that will wait for all the page resources to load before rendering. That might help you out.

**Comment by jonnnnyw** [comment]
The original issue has been solved so I'm going to close this. If you have any further issues feel free to open a new one.
