### ISSUE TITLE
Many phantomjs tasks per one request

### ISSUE THREAD

**Issue by andynador** [jonnnnyw/php-phantomjs#44]
Hello! The library you have wrote is good, it's easy to use. But I notice a problem, may be in my OS - in my htop sometimes I watch 3 or 4 running phantomjs tasks per one request, they are absolutely identical, I want to have only one task per one request. When I kill php proccess, which call Phantomjs, this tasks kill to. I have installed OS Ubuntu 12.04. Do you know, how can I resolve this issue?

**Comment by jonnnnyw** [comment]
Can you give me an example of how you are using this library?
