### ISSUE TITLE
Getting different results from running through PHP script compared to running directly with PhantomJS

### ISSUE THREAD

**Issue by fi5u** [jonnnnyw/php-phantomjs#49]
I have created a custom script that goes to a web page, fill in a search box with a query, submits the form and when the search results page is loaded it returns the new URL.

When I run this directly with Terminal (`phantomjs autotemplate.proc`), I get the successful results that I'm after. However, when I navigate in the browser to the php script that uses the custom *.proc* file, I generally get different results.

I say *generally* as for some URLs it works. Usually, with the php script, the custom Phantom script fails at `page.open()` returning a null response. The pages that fail with the PHP script return a successful response when the `.proc` file is run directly. It's difficult to tell exactly what is happening, but when the script fails, it seems to fail when the `.proc` script reaches `page.open()`. A response from `page.open()` is not even waited for as at this point `echo json_encode($response->content);` is output from the PHP. When running the custom Phantom script with PHP PhantomJS, with the URLs it fails with, it fails every time, with the URLs that work, they work every time. I have provided exit points throughout the `.proc` file - there should be no point that it exits with null.

Hopefully this makes sense. I can provide my code if that will help.

Have you come across this sort of inconsistency before? Is there anything obvious that I might be doing wrong? Is it possible that PHP PhantomJS could process the `.proc` file differently than running it directly with Phantom?

**Comment by jonnnnyw** [comment]
Hi, can you please provide your code and I will run some tests over it. It could be something to do with the phantomloader script which some people seem to be having trouble with. That script has been removed in version 4 which should be released in the next couple of weeks.

In the meantime I'll look into your code and see if I can figure it out.

**Comment by fi5u** [comment]
I think I've discovered what's causing the script to fail. The websites I access with the script that fail, all have some sort of console log error output. The ones that don't fail, do not output any error. Therefore, the fix was to put into the custom script a `page.onError()` to handle that.

That fixes it for my environment. However, I don't know whether it is intended that PHP PhantomJs fails if it encounters an unhandled error on the page (where Phantom JS direct would not fail). Perhaps this needs looking into. Many thanks.
