### ISSUE TITLE
I cannot install it with composer

### ISSUE THREAD

**Issue by Greg767** [jonnnnyw/php-phantomjs#50]
Hi,

I am having a problem with installing it with composer.
I've followed to the letter this page: http://jonnnnyw.github.io/php-phantomjs/
and when I launch the composer downloads php-phantomjs, at 100% it says zip is invalid and it retries 2 more times then it fails with a value exception.
Do you know whats wrong with it?

Thanks a lot
Greg

**Comment by jonnnnyw** [comment]
Hi Greg,

Not really sure what could be the problem here. Doesn't sound like it is related to the library itself. What version are you trying to install?

**Comment by Greg767** [comment]
Hi,
I would like to install the latest version and I thought the json that is
provided on the manual will do that. Apparently it tries to install 1.9.7
and I guess that's not the latest..  Could you please indicate how to get
the latest version?
Thank you very much.

Greg

**Comment by razum90** [comment]
Hi,
I'm having the same problem as Greg767 had. Did you find a solution for it?
Thanks

**Comment by Greg767** [comment]
Hi,

No, unfortunately I didn't find why it didn't install... I just abandoned.
Sorry.

2015-06-30 10:05 GMT+02:00 razum90 <notifications@github.com>:
