### ISSUE TITLE
Different margin properties for top, left, etc

### ISSUE THREAD

**Issue by skinit** [jonnnnyw/php-phantomjs#52]
Hello, the original phantomjs documentation describes the margin property as "can be provided as a single dimension or as an object containing one or more of the following properties: 'top', 'left', 'bottom', 'right' ...".

Single dimension settings are working fine for me with php-phantomjs, but I cant find a way to use different settings for 'top' and 'left' using an object or array as margin setting. Will this be supported in the future? 

In addition to this: Do you plan to support the repeating page header and footer properties of phantomjs?

Thank you in advance
Stephan

**Comment by jonnnnyw** [comment]
Support for single dimension margins will be in the next version which is about a week away. Will look into header/footer properties.

**Comment by jonnnnyw** [comment]
This has now been released in Version 4

**Comment by alexleonard** [comment]
@jonnnnyw Thanks for this great package, I was delighted to be able to get PDF generation setup quite quickly and with minimal confusion. 

Has there been any progress on providing a unified approach for repeating page header/footer for PDFs? I read through the custom scripts documentation but wasn't entirely sure how I should structure things to implement repeating header/footer manually - whether I need to override the procedure_pdf.partial or generate a full custom template.

Thanks!

**Comment by jonnnnyw** [comment]
Hi @alexleonard 

I have had someone else ask for the same thing so I will add it to the list. Would you mind creating a new issue for it so I can keep you updated and I will hopefully get to it next week.

**Comment by alexleonard** [comment]
Hey @jonnnnyw Sorry for the delay, created that issue now.
