### ISSUE TITLE
Undefined method

### ISSUE THREAD

**Issue by Zibeug** [jonnnnyw/php-phantomjs#53]
Hello,

I have a problem with the basic script when I load it I have this error  with debug flag : PHP Fatal error:  Call to undefined method JonnyW\PhantomJs\Client::debug() in C:\inetpub\wwwroot\composer\index.php on line 

nothing debug flag : PHP Fatal error:  Uncaught exception 'JonnyW\PhantomJs\Exception\InvalidMethodException' with message 'Invalid method provided: HTTP://GOOGLE.COM' in C:\inetpub\wwwroot\composer\src\JonnyW\PhantomJs\Http\AbstractRequest.php:126
Stack trace:
#0 C:\inetpub\wwwroot\composer\src\JonnyW\PhantomJs\Http\AbstractRequest.php(104): JonnyW\PhantomJs\Http\AbstractRequest->setMethod('http://google.c...')
#1 C:\inetpub\wwwroot\composer\src\JonnyW\PhantomJs\Http\MessageFactory.php(52): JonnyW\PhantomJs\Http\AbstractRequest->__construct('GET', 'http://google.c...', 5000)
#2 C:\inetpub\wwwroot\composer\index.php(11): JonnyW\PhantomJs\Http\MessageFactory->createRequest('GET', 'http://google.c...')
#3 {main}
  thrown in C:\inetpub\wwwroot\composer\src\JonnyW\PhantomJs\Http\Abst

What can I do ?

**Comment by pctin** [comment]
Hello, I have same problem but in Yii Framework.
@JonnnyW can you please help me to find the solution?

Yii::import('application.vendors.php-phantomjs-master.vendor.*');
require 'autoload.php';
use JonnyW\PhantomJs\Client;

$client = Client::getInstance();
$client->debug(true);

Exception:
Fatal error: Call to undefined method JonnyW\PhantomJs\Client::debug() in \protected\components\helpers\PhantomJsHelper.php on line 13

**Comment by jonnnnyw** [comment]
It looks like you are using the version 4 code which has changed from version 3. You can check out the latest documentation here: http://jonnnnyw.github.io/php-phantomjs/

Basically you want `$client->getEngine()->debug(true);`
