### ISSUE TITLE
Add an example on how to set the quality of a screen capture

### ISSUE THREAD

**Issue by sttoussaint** [jonnnnyw/php-phantomjs#54]
Hi,

The screen capture works great but I am not to set the quality.

It would be great to have an example or a method if it doesn't exist.

Thanks for your help and great work for your tool!

Stephan

**Comment by jonnnnyw** [comment]
This currently doesn't exist but I will add it to the list of things to look at for the next release.

**Comment by tlaverdure** [comment]
Sent a pull request to add this. https://github.com/jonnnnyw/php-phantomjs/pull/77

**Comment by jonnnnyw** [comment]
This has been merged and tagged in the 4.1.0 released. Will update docs shortly.

**Comment by tlaverdure** [comment]
Cool! Nice project, will see if I can pitch in as needed.

**Comment by moometric** [comment]
` $request->setQuality(100);`
