### ISSUE TITLE
Empty Response

### ISSUE THREAD

**Issue by atwellpub** [jonnnnyw/php-phantomjs#57]
I am using this code in a phpunit bootstrap and my response has it's structure but all the key values are empty. Any clue on what would cause this? 

```

require './vendor/autoload.php';

use JonnyW\PhantomJs\Client;

/**
*  Replacement for WordPress's wp_remote_get
*  processes javascript through PhantomJs
*/
function inbound_remote_get() {
	
	
	$phantomJs = Client::getInstance();
	$phantomJs->setBinDir( LANDINGPAGES_PATH .  'tests/bin/' );
	$phantomJs->setPhantomJs( LANDINGPAGES_PATH .  'tests/bin/phantomjs.exe');
	$phantomJs->setPhantomLoader( LANDINGPAGES_PATH . 'vendor/jonnyw/php-phantomjs/bin/phantomloader');
	
	$request  = $phantomJs->getMessageFactory()->createRequest();
	$response = $phantomJs->getMessageFactory()->createResponse();

	$request->setMethod('GET');
	$request->setUrl('http://inboundnow.com');

	$phantomJs->send($request, $response);

	if($response->getStatus() === 200) {
		echo $response->getContent();
	}

	print_r($response);
}

inbound_remote_get();
exit;
```

and my response looks like this:

```
JonnyW\PhantomJs\Message\Response Object
(
    [headers] => Array
        (
        )

    [status] =>
    [content] =>
    [contentType] =>
    [url] =>
    [redirectUrl] =>
    [time] =>
    [console] =>
)
```

**Comment by tostercx** [comment]
Are you on windows? Could be the slashes.

    proc_open('bin\\phantomjs.exe', [], $p); // works
    proc_open('bin/phantomjs.exe', [], $p); // fails

**Comment by zhang122562** [comment]
I have the same issue like you .Do you fix it now ?

**Comment by jonnnnyw** [comment]
Which version of the library are you using? If it is V4 then there is an issue related to PhantomJS 2 and  OS X - https://github.com/jonnnnyw/php-phantomjs/issues/75

If you are on OS X and having this issue then try installing UPX and running UPX on the PhantomJS executable.

```
upx -d /path/to/phantomjs
```
If you have Homebrew installed then you can install UPX using the following:

```
brew install upx
```

Otherwise grab it here http://upx.sourceforge.net/

**Comment by zhang122562** [comment]
V4 on win7

**Comment by zhang122562** [comment]
I install it via composer.Do you konw what‘s wrong with it? How can i fix this issue?

**Comment by jonnnnyw** [comment]
Try running your PhantomJS executable from the command line to check that it's working fine on your machine.

```
/path/to/phantomjs
```

That should put you in interactive mode. If so then run a script:

```
phantomjs> console.log("Hello, world!"); phantom.exit();
Hello, world!
```

If you can't get into interactive mode or the script fails then it is your executable.

You can also try setting the absolute path to your PhantomJS executable:

```
$client = Client::getInstance();
$client->getEngine()->setPath('/path/to/phantomjs');
```

You might want to play around with backslashes if you are on Windows, as mentioned in a post above:

```
$client = Client::getInstance();
$client->getEngine()->setPath('\\path\\to\\phantomjs.exe');
```

Lastly check that the permissions on your PhantomJS executable can allow it to be executed by your web server.

**Comment by zhang122562** [comment]
thx a lot.i fix this issue,just like what you say ,i setting the absolute path to the PhantomJS executable,and it works.thx you a lot.

**Comment by jonnnnyw** [comment]
Cool. Glad to help.

**Comment by Peace-N** [comment]
This worked for me on windows:
$client->getEngine()->setPath(__DIR__ . '/bin/phantomjs.exe');

**Comment by abhisheksaxena91** [comment]
Hi
This is working fine in my window system phantomjs> console.log("Hello, world!"); phantom.exit();
Hello, world!

but still get the issue of empty response i am setting the path like this
$client->getEngine()->setPath('/var/www/stratus/public/bin/phantomjs.exe');

backslashes showing the error of file is not executable
