### ISSUE TITLE
no setType for createCaptureRequest

### ISSUE THREAD

**Issue by aoiserizawa** [jonnnnyw/php-phantomjs#61]
i was trying to save the image with my custom proc but it doesnt run because theres no setType in createCaptureRequest. can somebody help me? TIA

<?php
    require __DIR__ . '/vendor/autoload.php';
    
    use JonnyW\PhantomJs\Client;
    use JonnyW\PhantomJs\DependencyInjection\ServiceContainer;

    $requestLink = 'https://www.google.com.ph/?gfe_rd=cr&ei=ZyaBVYqdK-zC8AfBsoG4CA&gws_rd=ssl#q=surfing&num=200';

    $location = './';

    $serviceContainer = ServiceContainer::getInstance();

    $procedureLoader = $serviceContainer->get('procedure_loader_factory')
                    ->createProcedureLoader($location);

    $client = Client::getInstance();

    $client->getProcedureLoader()->addLoader($procedureLoader);

    //$request = $client->getMessageFactory()->createRequest($requestLink,'GET');

     $request = $client->getMessageFactory()->createCaptureRequest($requestLink,'GET');

    $file = './captures/';
    
    $top    = 10;
    $left   = 10;
    $width  = 200;
    $height = 400;
    
    $setCaptured = $request->setCaptureFile($file);

    $request->setCaptureDimensions($width, $height, $top, $left);

    $request->setType('scrape2');

    $response = $client->getMessageFactory()->createResponse();

    $client->send($request, $response);

    echo "<pre>";
    var_dump($response->content);
    echo "</pre>";

**Comment by jonnnnyw** [comment]
Set type has been added to the 4.* release.
