### ISSUE TITLE
Composer RuntimeException

### ISSUE THREAD

**Issue by jonaslejon** [jonnnnyw/php-phantomjs#65]
When running composer.

Composer version 1.0-dev (3d962879a8bb9874a6d8b2eeb90f3d13b153d174) 2015-08-14 13:55:08

$ php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

  [RuntimeException]
  Could not scan for classes inside "src/" which does not appear to be a file nor a folder

**Comment by jonnnnyw** [comment]
I think this is related to composer rather than this library so you might want to raise your question with them.
