### ISSUE TITLE
Need pdf support, version 4.0 is stable?

### ISSUE THREAD

**Issue by saifabbasi** [jonnnnyw/php-phantomjs#66]
I need Pdf support , but it is in version 4.0 which is not yet merged in master version, can i install 4.0 directly? is it stable? are you planning to merge in master version?

**Comment by jonnnnyw** [comment]
It's stable but I've been waiting for the PhantomJS guys to solve an issue they've been having with compiling generic Linux distros for PhantomJS v2.0. Looks like they aren't going to solve that problem so PhantomJS will need to be compiled and installed manually when installing the new version of this library.

I will update the docs for v4.0 and get a stable release out in the next week. A few things have changed in the new version but feel free to test the development branch in the meantime. Feedback is appreciated.

**Comment by jonnnnyw** [comment]
V4 was released a couple of weeks ago which includes PDF support.
