### ISSUE TITLE
Phantomloader not here in bin directory.

### ISSUE THREAD

**Issue by irfanwv** [jonnnnyw/php-phantomjs#67]
Hello, I have installed successfully on Linux debian. I can run js file's using exec(); But not Jonnnnyw PHP-Phantomjs. I am observe that phantomloader not found in bin directory. At the time of installation Carefully follow all instruction. What can I do?

**Comment by juanjolainez** [comment]
I'm exactly where you are. Have you found any solutions?

**Comment by irfanwv** [comment]
Thank's for your response,
I am still on this stage, is permission create any problem?

**Comment by juanjolainez** [comment]
Nope, I tried to run the composer with root (to see if it wasn't created because of permissions) and the result was the same. It says that the installation was well, but phantomloader is not there, just phantomjs

**Comment by irfanwv** [comment]
But, I can run js file's by exec(); and You?

**Comment by juanjolainez** [comment]
Do you mean running specific PhantomJS code or any javascript file?

**Comment by irfanwv** [comment]
PhantomJs code

**Comment by frazehmad** [comment]
Try this

``` $client->setBinDir('/PATH/TO/BIN');

**Comment by irfanwv** [comment]
Thanks for response,
But main thing is phantomloader not here in bin directory.

**Comment by frazehmad** [comment]
Probably you need to remove "bin" folder and remove "jonnyw/php-phantomjs" from your composer.json file then run composer update again to remove everything.

Basically you need to refresh it. I also had same issue and this way it was solved.

**Comment by vblinden** [comment]
The way I fixed this.

  - Delete the vendor folder.
  - Clear composer cache.
  - Composer install.

Also see issue #63

**Comment by jonnnnyw** [comment]
@vblinden is correct - just remove everything in your vendor folder and do a composer install.

Side note - version 4 has just been released and the phantomloader file has been deprecated so might be worth upgrading
