### ISSUE TITLE
Map $client->setBinDir() to engine->setPath()

### ISSUE THREAD

**Issue by sigma-z** [jonnnnyw/php-phantomjs#71]
In Comments and Documentation I found many places where it was suggested to set the binary directory by calling: $client->setBinDir(), but this method does not exists (anymore?). So my suggestion is to map method setBinDir() in class Client:

```php
public function setBinDir($binDir)
{
    $this->engine->setPath($binDir);
}
```

**Comment by pctin** [comment]
Yes, there are many methods still don't exists:
- debug
- addOption
...

This is perfect tool to run Phantomjs with PHP, hope this will be fixed soon!

**Comment by jonnnnyw** [comment]
Hi, the documentation is for version 3. If you are using master or the v4 branch then the documentation won't be inline. I will put the v4 documentation up when I get a moment (it has been written). I suggest using the v3 tag in the meantime.

**Comment by pctin** [comment]
Ah, yes I'm using the master brand. I think you should add this note to the document also.

By the way, after I using v3.1.5, i get the error #22  
I'm using xampp in windows, check there is phantomloader in bin folder but get the error

I comment validate phantomloader file and it looks work but then I got the error: #41

**Comment by jonnnnyw** [comment]
Closing this issue but will update the ones you have referenced.
