### ISSUE TITLE
Capture file is not writeable by PhantomJs: ../bin/file.jpg

### ISSUE THREAD

**Issue by patelchirag123** [jonnnnyw/php-phantomjs#72]
Capture file is not writeable by PhantomJs: ../bin/file.jpg This Error is Give and I GIve a Write Permission on my main folder still it give me error so plz replay me

**Comment by jonnnnyw** [comment]
Chances are the directory isn't writable by your web server. I would suggest checking the permissions again. Also, try using an absolute path so you can be sure you're trying to save it in the correct place.
