### ISSUE TITLE
$client->getProcedureCompiler() does not exists!

### ISSUE THREAD

**Issue by Razinsky** [jonnnnyw/php-phantomjs#75]
Taken from:
http://jonnnnyw.github.io/php-phantomjs/4.0/caching/

The getProcedureCompiler() method does not event exists in the Client class.

**Comment by jonnnnyw** [comment]
Thanks for pointing that out. It appears to be an oversight on my part. Will get a patch release up.

**Comment by Razinsky** [comment]
No problem. By the way I'm having a very hard time right now trying to make php-phantomjs to work. I always get an empty response and an empty log. I activated debug and disabled cache and now I'm echoing everywhere to understand why it doesn't work...

Seems that stream_get_contents in Procedure::run doesn't return anything.

Is there something I'm missing? Anything, a PHP library, a php.ini setting?

**Comment by jonnnnyw** [comment]
I would say it would be your phantomjs install. Make sure the path to the executable is correct and your server has permissions to run it. What OS are you on?

**Comment by Razinsky** [comment]
I used the PhantomInstaller script you suggest to put in the composer.json before installing the package. I get no PhantomJS exception so I guess I point to the correct path. Permissions to execute are good.
I'm on OSX 10.11.2

**Comment by jonnnnyw** [comment]
Alright, I've got the same version of OS X in my dev environment so it probably isn't that. Have you tried requesting different a couple of different just to make sure it's not the website?

If your could provide a code snippet to I can try running it.

**Comment by Razinsky** [comment]
Yep I'm trying on google.com right now ;) Here's the exact code I'm running. Thank you for your help mate.

<pre>
$client = Client::getInstance();
$client->getEngine()->debug(true);
$client->getProcedureCompiler()->disableCache();
$client->getEngine()->setPath(__DIR__.'/../../vendor/phantomjs');

/** 
 * @see JonnyW\PhantomJs\Message\Request 
 **/
$request = $client->getMessageFactory()->createRequest('http://google.com', 'GET');

/** 
 * @see JonnyW\PhantomJs\Message\Response 
 **/
$response = $client->getMessageFactory()->createResponse();

// Send the request
$client->send($request, $response);

if($response->getStatus() === 200) {

    // Dump the requested page content
    echo $response->getContent();
}
else{
	print_r($response);
}
</pre>

**Comment by jonnnnyw** [comment]
Weirdly I've had problems with Phantomjs and google.com before. It doesn't seem to return a response for some reason. That and MySpace... 

I'm just on a train at the moment but will give your code a go later when I'm at a computer.

**Comment by Razinsky** [comment]
Ok great. I'm trying to reach a local URL but that shouldn't be the problem too. I just tried to reach my own website with no success again..

**Comment by Razinsky** [comment]
Well it seems that phantomjs gets killed everytime I run it even in the Terminal: <code>[1]    17627 killed</code>

I'll dig further.

**Comment by jonnnnyw** [comment]
Does replacing the phantomjs executable with this one sole your issue?

https://github.com/eugene1g/phantomjs/releases

**Comment by Razinsky** [comment]
Hahaha nice I was exactly about to try that. I'm trying to install UPX first. I'll keep you posted.

**Comment by jonnnnyw** [comment]
Cool, let me know. If we know what it is then I can add some checks in the installer to work around it.

**Comment by Razinsky** [comment]
Got it working with the UPX trick:

<code>$ brew install upx</code>
<code>$ upx -d /path/to/phantomjs</code>

Voila!

**Comment by jonnnnyw** [comment]
Great, thanks for looking into that. I want to write an installer into the library so I will include this into it.

**Comment by zhang122562** [comment]
I fix this issue by two steps，as the fllow;
first：add a getProcedureCompiler()   in the ClientInterface.php like this
         public function getProcedureCompiler();
second：add a getProcedureCompiler() function to Client.php like this 
public function getProcedureCompiler()
    {
        return $this->procedureCompiler;
    }
Hope this will help you.

**Comment by tlaverdure** [comment]
Sent a pull request for this. https://github.com/jonnnnyw/php-phantomjs/pull/77

**Comment by jonnnnyw** [comment]
Merged and tagged in the 4.1.0 release.
