### ISSUE TITLE
Phantom 2.0.0 Gone from bitbucket

### ISSUE THREAD

**Issue by mayrop** [jonnnnyw/php-phantomjs#80]
https://bitbucket.org/ariya/phantomjs/downloads/

`The "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2" file could not be downloaded (HTTP/1.1 404 NOT FOUND)  `

`https://github.com/jakoch/phantomjs-installer/releases/tag/2.1.1`

**Comment by jonnnnyw** [comment]
No Linux compiled executables were available for PhantomJS 2.0 so you were required to compile your own. PhantomJS 2.1.1 has just been released which does have them so I have upgraded this library with the new version.

I recommend upgrading to version 4.2.*.
