### ISSUE TITLE
Twig_Loader_String Error

### ISSUE THREAD

**Issue by matwils** [jonnnnyw/php-phantomjs#84]
Hello,

I just updated my composer.json file from php-phantomjs version 3.* to version 4.* and am now getting the following error when using phantomjs:

```
The Twig_Loader_String class is deprecated since version 1.18.1 and will be removed in 2.0. Use Twig_Loader_Array instead or Twig_Environment::createTemplate().

The "phantomjs.twig.string_loader" service relies on the deprecated "Twig_Loader_String" class. It should either be deprecated or its implementation upgraded.
```

Any help on how to fix this would be greatly appreciated.

Thanks,

Matt

**Comment by wwendorf** [comment]
I'm having the same problem.  Not sure where or how to fix this.  Am switching to v3 for now to see if it works under v3.

**Comment by wwendorf** [comment]
If I switch to "jonnyw/php-phantomjs": "3.*" in composer.json, I get this error:

Not quoting the scalar "@phantomjs.procedure.procedure_factory" starting with "@" is deprecated since Symfony 2.8 and will throw a ParseException in 3.0.

**Comment by jonnnnyw** [comment]
Sorry for the lateness on this, have been on holiday. Will release a fix for this in the morning (GMT).

**Comment by wwendorf** [comment]
Thanks.  Can you please comment when done so I get an email on it? 

I appreciate the quick fix!

Wade

**Comment by jonnnnyw** [comment]
This has been patched in v4.3.1. Let me know how you get on.

**Comment by wwendorf** [comment]
Hi Jonnnyw, I updated and it doesn't give me those errors anymore, but it is also not saving the screen capture.  The bin dir is 777 permissions with the same owner as the rest of the laravel app.  Any suggestions?

**Comment by wwendorf** [comment]
Here's my code:

`		$client = Client::getInstance();
		$client->getEngine()->setPath('../bin');
		
		$request  = $client->getMessageFactory()->createCaptureRequest(Input::get('url'));
		$response = $client->getMessageFactory()->createResponse();
		
		$filename = 'screenshot' . Carbon::now()->format('Y-m-d-H:i:s') . ".jpg";
		$file = '../bin/' . $filename;
		
		$request->setOutputFile($file);
		
		$client->send($request, $response);
		
		rename($file, 'screenshots/' . $filename);
		
		echo '<img src="screenshots/' . $filename . '>';`

**Comment by wwendorf** [comment]
Ok, more information:

sh: 1: ../bin: Permission denied

However, the permissions for that directory are set to 777

**Comment by jonnnnyw** [comment]
I would set your bin path to an absolute path not a relative 1

**Comment by wwendorf** [comment]
Tried that too.

**Comment by wwendorf** [comment]
I have tried setting the bin path the /usr/bin (location phantomjs was installed to with an apt-get) and /vagrant/bin

**Comment by jonnnnyw** [comment]
Closing this ticket as the original issue is fixed. Please refer to the other tickets for your additional issue.
