### ISSUE TITLE
phantomjs always returns empty JonnyW\PhantomJs\Http\Response

### ISSUE THREAD

**Issue by tumdav** [jonnnnyw/php-phantomjs#86]
### Request
```php
$client = Client::getInstance();
$client->getEngine()->setPath(Yii::getAlias("@app/web/phantombin/phantomjs"));
$request = $client->getMessageFactory()->createRequest();
$response = $client->getMessageFactory()->createResponse();
$request->setMethod('GET');
$request->setUrl('http://google.com');
$client->send($request, $response);
var_dump($response);
```

### Response
```php
object(JonnyW\PhantomJs\Http\Response)#212 (8) {
  ["headers"]=>
  array(0) {
  }
  ["status"]=>
  NULL
  ["content"]=>
  NULL
  ["contentType"]=>
  NULL
  ["url"]=>
  NULL
  ["redirectURL"]=>
  NULL
  ["time"]=>
  NULL
  ["console"]=>
  NULL
}
```

I have installed php phantomjs 1.9.8 in my ubuntu server.
No any errors , but not response.why???

**Comment by jboiss** [comment]
I'm having the same issue. I do have this working on another site, so I'm trying to find the difference between setups.

**Comment by jboiss** [comment]
The solutions for me was to install phantomjs from my package manager and refer the engine to it, rather than the binary downloaded by composer. 

` $this->client->getEngine()->setPath('/usr/bin/phantomjs');`

**Comment by tumdav** [comment]
I installed phantomjs and set the path to the executable file.
My server RAM is 512MB it can cause problem ?

**Comment by jboiss** [comment]
In my case it was clearly a problem with the binary download by composer. Try to run the binary from the command line. It ran on my Mac host -- but in my Ubuntu virtual machine it failed with:

`./phantomjs: cannot execute binary file: Exec format error`

This library doesn't pick up the error message and returns a response object filled with null properties.

**Comment by jonnnnyw** [comment]
As mentioned by @jboiss the most common cause for this issue is that the bundled binaries are incompatible with your system. In this case I would recommend [downloading PhantomJS](http://phantomjs.org/download.html) and pointing the library at the executable:

`$client->getEngine()->setPath('/path/to/phantomjs');`

The bundled binaries will most likely be removed in the next major release in favour of manual download as they don't seem to work for everyone.
