### ISSUE TITLE
Generate pdf from web page which is under authentification

### ISSUE THREAD

**Issue by trossier** [jonnnnyw/php-phantomjs#89]
Hello :-),

I'm working with your bundle and i have 2 questions:
- first, how can i generate a pdf from a web page which is under security authentification ?
- Second, how can i generate header and footer,  i have to use a custom script ?

Thanks for your help :-)

Have a good day

Tom

**Comment by trossier** [comment]
Hi

So i succeed to generate a pdf from a web page which is under authentification :-D

Now in would like to generate a footer and header.

Apparently no method exist for the moment, so i try with partial but i have difficulty.

My code:

`$location = '/var/www/partial/';
    
    $serviceContainer = ServiceContainer::getInstance();
    
    $procedureLoader = $serviceContainer->get('procedure_loader_factory')
        ->createProcedureLoader($location);
        
    $client = Client::getInstance();
    $client->getProcedureLoader()->addLoader($procedureLoader);

    $client->getEngine()->setPath('/path/bin/phantomjs');

    $request  = $client->getMessageFactory()->createPdfRequest('http://jonnyw.me/');
    
    $request->setHeaders([
        'Authorization'=>'Basic '.  base64_encode('user:pxd'),
    ]);
    
        $response = $client->getMessageFactory()->createResponse();
    
    $file = '/var/www/document.pdf';
    
    $request->setOutputFile($file);
    
    $client->send($request, $response);`

And my partial code below:
`{% if input.getType() == 'pdf' %}

    var paperWidth       = '{{ input.getPaperWidth() }}',
        paperHeight      = '{{ input.getPaperHeight() }}',
        paperFormat      = 'A3',
        paperOrientation = '{{ input.getOrientation() }}',
        paperMargin      = '{{ input.getMargin() }}';
    
    if(paperWidth && paperHeight) {
        
        debug.push(new Date().toISOString().slice(0, -5) + ' [INFO] PhantomJS - Set page size ~ width: ' + paperWidth + ' height: ' + paperHeight + ' margin: ' + paperMargin);
        
        page.paperSize = { 
            width:  paperWidth, 
            height: paperHeight, 
            margin: paperMargin 
        };

    } else {
        
        debug.push(new Date().toISOString().slice(0, -5) + ' [INFO] PhantomJS - Set page size ~ format: ' + paperFormat + ' orientation: ' + paperOrientation + ' margin: ' + paperMargin);
        
        page.paperSize = { 
            format:      paperFormat, 
            orientation: paperOrientation, 
            margin:      paperMargin 
        };
        
    }

{% endif %}`

I change the default value for paperFormat  = 'A3', but it 's always in A4 format.

Maybe i forgot something? can you help me?

Thanks

Tom

**Comment by jonnnnyw** [comment]
This should be working but I will take a look

**Comment by jonnnnyw** [comment]
A repeating header and footer can now be added.

```
$request  = $client->getMessageFactory()->createPdfRequest('http://jonnyw.me/');
$request->setRepeatingHeader('<h1>Header <span style="float:right">%pageNum% / %pageTotal%</span></h1>'[, height]);
$request->setRepeatingFooter('<footer>Footer <span style="float:right">%pageNum% / %pageTotal%</span></footer>'[, height]);
```

Paper format can also be changed.

```
$request  = $client->getMessageFactory()->createPdfRequest('http://jonnyw.me/');
$request->setFormat('A3');
```
