### ISSUE TITLE
Cannot set background

### ISSUE THREAD

**Issue by pablomoreno61** [jonnnnyw/php-phantomjs#92]
Hi!

Could be possible to set a transparent background or color background to a generated image?

**Comment by mrwhale** [comment]
This would be nice to know. currently having an issue where it saves screenshots with a black background if no other is specified by the site - similar to https://github.com/ariya/phantomjs/issues/12724

**Comment by Dondeal** [comment]
I am experiencing the same problem, as well. I would love to set the background to white instead of black.

**Comment by twindual** [comment]
Hi @pablomoreno61, @mrwhale, @Dondeal.

Here is a code snippet to set the background white from the following page, [http://phantomjs.org/tips-and-tricks.html](http://phantomjs.org/tips-and-tricks.html) 

**Page background color**

PhantomJS does not set the background color of the web page at all, it is left to the page to decide its background color. If the page does not set anything, then it remains transparent.

To force a certain color for the web page background, use the following code:

`page.evaluate(function() {
  document.body.bgColor = 'white';
});`

Make sure this is executed before calling render() function of the web page.

**Comment by pablomoreno61** [comment]
Hi @twindual ,

I saw that option before, but I want to do it directly using the php library, not within a custom JS file

**Comment by jonnnnyw** [comment]
Will add this functionality in the next couple of days

**Comment by maxiwheat** [comment]
Would be appreciated! +1

**Comment by pablomoreno61** [comment]
great!!! +1

2016-04-26 19:26 GMT+02:00 maxiwheat <notifications@github.com>:

**Comment by jonnnnyw** [comment]
Version 4.4.0 now lets you set the styles on the body tag of the requested page.

Usage:

```
$request  = $client->getMessageFactory()->createRequest();
$request->setBodyStyles(array(
     'backgroundColor' => '#ff0000'
));
```

It can also be used to set other CSS styles on the body tag if desired.

[Documentation](http://jonnnnyw.github.io/php-phantomjs/4.0/3-usage/#set-background-color)

**Comment by mrwhale** [comment]
You the man jonnnnyw!

**Comment by pablomoreno61** [comment]
it works like a charm!

thanks @jonnnnyw

2016-05-04 15:08 GMT+02:00 Jonny Wenmoth <notifications@github.com>:

**Comment by zuups** [comment]
Thanks a lot! The problem is that it overwrites existing body background color (if any) and also doesn't apply to frameset. In my case, solution was writing .png instead of .jpg:

`$request->setFormat('png');`
