### ISSUE TITLE
composer update/install fails

### ISSUE THREAD

**Issue by pablomoreno61** [jonnnnyw/php-phantomjs#97]
I'm getting this error while trying to update the package:

> PhantomInstaller\Installer::installPhantomJS
Script PhantomInstaller\Installer::installPhantomJS handling the post-install-cmd event terminated with an exception

  [RuntimeException]
  Can not determine required version of jakoch/phantomjs-installer

**Comment by SoldierCorp** [comment]
Same problem here, using Laravel 4.2

**Comment by b-d-b** [comment]
Very new to PHP, no idea how to even work around this.  @SoldierCorp or @pablomoreno61  have any idea how I can get a previous version installed?

**Comment by jonnnnyw** [comment]
I have patched this in v4.3.2 which should solve this issue. Can you please confirm.

**Comment by gorillaedan** [comment]
I get this error when run omposer require "jonnyw/php-phantomjs:4.*"

![screenshot_215](https://cloud.githubusercontent.com/assets/5723337/14683459/f8de81d6-0754-11e6-99d3-33446247efee.png)

**Comment by jonnnnyw** [comment]
Strange... do you already have an older version required/installed? I just tried a clean install using the command you posted and it worked fine.

Check that you have the following in your `composer.json` file, under the the `require` key:

`"jonnyw/php-phantomjs": "4.*"`

If you do and it's still not working then as a last resort you could delete your vendor folder and `composer.lock` file and run `composer update`.

**Comment by b-d-b** [comment]
@jonnnnyw  That actually worked.  Removed my vendor folder, removed my lock file, and triggered an update.  Thank you so much for issuing this update.

**Comment by jonnnnyw** [comment]
No problem

**Comment by pablomoreno61** [comment]
Hi @jonnnnyw , I've already installed the latest version without removing vendor folder. Executing "composer install" throws an error "Can not determine required version of jakoch/phantomjs-installer", but executing "composer update" works perfectly.

thanks!
