### ISSUE TITLE
Cache is not saved.

### ISSUE THREAD

**Issue by aboldin** [jonnnnyw/php-phantomjs#98]
I use this SDK in different requests, and, as i can see in my /tmp folder - phantomJs cache is removed every time, script finished. But how can i keep pages cached forever (like chrome and others)? All i found in internet - enable disk-cache and increase disk cache size, but how can i do something like this using this SDK? 
Sorry for my bad english..

**Comment by jonnnnyw** [comment]
You can add additional PhantomJS options using the `addOption` method:

```
$client = Client::getInstance();
$client->getEngine()->addOption('--disk-cache=true');
$client->getEngine()->addOption('---max-disk-cache-size=[size]');
```

[Documentation](http://jonnnnyw.github.io/php-phantomjs/4.0/3-usage/#phantomjs-options)

Let me know if this solves your issue.

**Comment by aboldin** [comment]
Yap, that's it, everything is fast now, THANKS!

Missed this in documentation =(
